# Generated by Django 3.1 on 2020-08-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20200821_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posting',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterField(
            model_name='posting',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
